# Generated by Django 3.2.8 on 2021-10-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('NASDAQ', 'NASDAQ'), ('NYSE', 'NYSE'), ('NYSE_ARCA', 'NYSE_ARCA'), ('NYSE_AM', 'NYSE_AM'), ('OTC', 'OTC'), ('AMEX', 'AMEX')], default='NASDAQ', max_length=10)),
                ('symbol', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stocks', models.ManyToManyField(related_name='portfolios', to='api.Stock')),
            ],
        ),
    ]
